<?php

/**
 * @category    Ecomtech
 * @package     Ecomtech_Savemypaquet
 * @author      Savemypaquet ( http://www.savemypaquet.com)
 * @developer   Ahmed MAHI <ahmed@mahi.ma> (http://ahmedmahi.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $session = Mage::getSingleton('core/session');?>
<fieldset>

<!-- Form Name -->
<legend><span class="logo-smp">Save<strong>My</strong>Paquet<sup>®</sup></span> - coordonnées client supplémentaires</legend>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="email">Émail *</label>
  <div class="col-md-8">
  <input id="email" name="smp[email]" type="text" placeholder="" class="form-control input-md input-text required-entry validate-email" required="" value="<?php echo $this->getInfosQuote()->getEmail() ?>">

  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="tel">Téléphone *</label>
  <div class="col-md-8">
  <input id="tel" name="smp[tel]" type="text" placeholder="" class="form-control input-md input-text required-entry" required="" value="<?php echo $this->getInfosQuote()->getTelephone() ?>" >

  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="batiment">Bâtiment</label>
  <div class="col-md-8">
  <input id="batiment" name="smp[batiment]" type="text" placeholder=""  value="<?php echo $session->getSmypClientBatiment() ?>" class="form-control input-md">

  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="etage">Étage *</label>
  <div class="col-md-8">
  <input id="etage" value="<?php echo $session->getSmypClientEtage() ?>" name="smp[etage]" type="text" placeholder="" class="form-control input-md input-text required-entry" >

  </div>
</div>

<!-- Multiple Radios (inline) -->
<div class="form-group">
  <label class="col-md-4 control-label" for="porte_position">Position de la porte *</label>
  <div class="col-md-8">
    <label class="radio-inline" for="porte_position-0">
      <input type="radio" name="smp[porte_position]" id="porte_position-0" value="1ère" required="" class="input-radio validate-one-required-by-name">
      1ère
    </label>
    <label class="radio-inline" for="porte_position-3">
      <input type="radio" name="smp[porte_position]" id="porte_position-3" value="2ème">
      2ème
    </label>
    <label class="radio-inline" for="porte_position-2">
      <input type="radio" name="smp[porte_position]" id="porte_position-2" value="3ème">
      3ème
    </label>
        <label class="radio-inline" for="porte_position-1">
      <input type="radio" name="smp[porte_position]" id="porte_position-1" value="autre">
      autre
    </label>
  </div>
</div>

<!-- Text input-->
<div class="form-group" id="porte_position">
  <label class="col-md-4 control-label" for="porte_position_autre"></label>
  <div class="col-md-8">
  <input id="porte_position_autre" name="smp[porte_position_autre]" type="text" placeholder="autre" class="form-control input-md input-text required-entry">

  </div>
</div>

<!-- Multiple Radios (inline) -->
<div class="form-group">
  <label class="col-md-4 control-label" for="porte_cote">Par rapport à l’escalier *</label>
  <div class="col-md-8">
    <label class="radio-inline" for="porte_cote-0">
      <input type="radio" name="smp[porte_cote]" id="porte_cote-0" value="0" required="" class="input-radio validate-one-required-by-name" >
      droite
    </label>
    <label class="radio-inline" for="porte_cote-1">
      <input type="radio" name="smp[porte_cote]" id="porte_cote-1" value="1"  >
      gauche
    </label>
    <label class="radio-inline" for="porte_cote-2">
      <input type="radio" name="smp[porte_cote]" id="porte_cote-2" value="2" >
      face
    </label>
  </div>
</div>

<!-- Multiple Radios (inline) -->
<div class="form-group">
  <label class="col-md-4 control-label" for="digicode">Digicode</label>
  <div class="col-md-8">
    <label class="radio-inline" for="digicode-0">
      <input type="radio" name="smp[digicode]" id="digicode-0" value="0" >
      Non
    </label>
    <label class="radio-inline" for="digicode-1">
      <input type="radio" name="smp[digicode]" id="digicode-1" value="1">
      Oui
    </label>
  </div>
</div>

<!-- Text input-->
<div class="form-group" id="digicode">
  <label class="col-md-4 control-label" for="digicode_value"></label>
  <div class="col-md-8">
  <input id="digicode_value" name="smp[digicode_value]" type="text" placeholder="Digicode" class="form-control input-md input-text required-entry">

  </div>
</div>

<!-- Multiple Radios (inline) -->
<div class="form-group">
  <label class="col-md-4 control-label" for="digicode2">2éme Digicode</label>
  <div class="col-md-8">
    <label class="radio-inline" for="digicode2-0">
      <input type="radio" name="smp[digicode2]" id="digicode2-0" value="0" >
      Nom
    </label>
    <label class="radio-inline" for="digicode2-1">
      <input type="radio" name="smp[digicode2]" id="digicode2-1" value="1">
      Oui
    </label>
  </div>
</div>

<!-- Text input-->
<div class="form-group" id="digicode2">
  <label class="col-md-4 control-label" for="digicode2_value"></label>
  <div class="col-md-8">
  <input id="digicode2_value" name="smp[digicode2_value]" type="text" placeholder="2éme Digicode" class="form-control input-md input-text required-entry">

  </div>
</div>

<!-- Multiple Radios (inline) -->
<div class="form-group">
  <label class="col-md-4 control-label" for="interphone">Interphone *</label>
  <div class="col-md-8">
    <label class="radio-inline" for="interphone-0">
      <input type="radio" name="smp[interphone]" id="interphone-0" value="0" required="" class="input-radio validate-one-required-by-name">
      Non
    </label>
    <label class="radio-inline" for="interphone-1">
      <input type="radio" name="smp[interphone]" id="interphone-1" value="1">
      Oui
    </label>
  </div>
</div>

<!-- Text input-->
<div class="form-group" id="interphone">
  <label class="col-md-4 control-label" for="interphone_value"></label>
  <div class="col-md-8">
  <input id="interphone_value" name="smp[interphone_value]" type="text" placeholder="Nom" class="form-control input-md">

  </div>
</div>

<!-- Button -->
<div class="form-group">
  <label class="col-md-4 control-label" for="button">Valider</label>
  <div class="col-md-8">
    <button id="button_smp" type="button" name="smp[button]" onclick="savemypaquet.ajaxForm(true)" class="btn btn-inverse" >Valider</button>
  </div>
</div>
</fieldset>
    <div class="savemypaquet_info">
    <label><?php echo $this->__('Validation Save My Paquet') ?></label>
    <span id="savemypaquet_validation_please_wait" class="please-wait" style="display: none;"><img src="<?php echo $this->getSkinUrl('images/savemypaquet/loader.gif') ?>" class="v-middle"> Chargement...</span>
<span id="savemypaquet_info">
     <?php if (!$this->validatePostCode()): ?>
    <div class="err"><?php echo $this->__('Attention le code postal (' . $this->getInfosQuote()->getPostcode() . ') saisie  n\'appartient pas au département (' . $this->getInfosQuote()->getRegionCode() . ') sélectionné') ?> </div>
 <?php endif;?>
</span>

</div>
<script type="text/javascript">
 //<![CDATA[
   savemypaquet.addFormButtonsEven();
  //]]>
 </script>
