<?php

/**
 * @category    Ecomtech
 * @package     Ecomtech_Savemypaquet
 * @author      Savemypaquet ( http://www.savemypaquet.com)
 * @developer   Ahmed MAHI <ahmed@mahi.ma> (http://ahmedmahi.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<script type="text/javascript">
 //<![CDATA[
var savemypaquet = new Varien.Savemypaquet("<?php echo Mage::getUrl('savemypaquet/index/form'); ?>","<?php echo $this->getSkinUrl('images/savemypaquet/') ?>");
 //]]>
 </script>
<?php echo $this->getChildHtml('oldshippingmethod'); ?>
